version: "3"
services: 
  spring-boot-app: 
    image: spring-boot-app
    restart: always
    build: .
    ports:
     - 9080:8099
    environment: 
      MYSQL_HOST: mysqlamk
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      
  mysqlamk:
   container_name: mysqlamk
   image: mysql
   ports:
    - 3307:3306
   environment: 
     MYSQL_DATABASE: test
     MYSQL_ROOT_PASSWORD: root